option(ZOB_WITH_ASAN         "build with address sanitizers suppport (if available)"         OFF)
option(ZOB_WITH_MSAN         "build with memory sanitizer suppport (if available)"           OFF)
option(ZOB_WITH_TSAN         "build with thread sanitizer suppport (if available)"           OFF)
option(ZOB_WITH_TESTS        "build the unit tests"                                          ON)
option(ZOB_WITH_LIBCPP       "use libc++ instead of default libstdc++ (if applicable)"       OFF)
